# Generated by Django 5.2.7 on 2025-11-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pzJourney', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('screenshot', models.ImageField(upload_to='admin_screenshots/')),
                ('screenshot_type', models.CharField(choices=[('learning_journey', 'Learning Journey Admin'), ('about_me', 'About Me Admin'), ('general', 'General Admin')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
