# Generated by Django 5.2.7 on 2025-11-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pzJourney', '0002_adminscreenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload your profile picture', null=True, upload_to='profile_pictures/'),
        ),
    ]
